#!/usr/bin/env bash
set -euo pipefail

expected="f14edb4770a1e58147b4b3efb2c4d47d79c44822"
test "$(git rev-parse HEAD)" = "$expected"

git fetch --no-tags origin main:refs/remotes/origin/main m1-integrated-20260630:refs/remotes/origin/m1-integrated-20260630
git branch -f main refs/remotes/origin/main
git checkout -B m1-integrated-20260630 "$expected"

package_lock_state="tracked"
if ! git ls-files --error-unmatch package-lock.json >/dev/null 2>&1; then
  package_lock_state="generated-untracked-for-npm-ci"
  npm install --package-lock-only --ignore-scripts --no-audit --no-fund
fi

rm -rf package-out /tmp/Noditech
mkdir -p package-out /tmp/Noditech

git bundle create package-out/noditech_m1.bundle main m1-integrated-20260630
git bundle verify package-out/noditech_m1.bundle > package-out/BUNDLE_VERIFY.txt 2>&1

git archive --format=zip --output=package-out/noditech_m1_worktree.zip m1-integrated-20260630
zip -q package-out/noditech_m1_worktree.zip package-lock.json

rsync -a --exclude 'node_modules/' --exclude 'dist*/' --exclude 'package-out/' "$GITHUB_WORKSPACE/" /tmp/Noditech/
(
  cd /tmp
  zip -qry "$GITHUB_WORKSPACE/package-out/Noditech_repo_with_git.zip" Noditech \
    -x 'Noditech/node_modules/*' 'Noditech/dist*/*' 'Noditech/package-out/*'
)

test -f package.json
test -f package-lock.json
test -f build/assemble-pc2-ll-release.js
test -f docs/MILESTONE1_FREEZE_TRANSITION.md
test -f docs/MILESTONE1_IMPLEMENTATION_STATUS.md
test -d .github/workflows
test -d chromium
test -d tests

cat > package-out/ENV.txt <<EOF
Repository: Simsalabim-png/Noditech
Checked-out branch: m1-integrated-20260630
Exact implementation head: $(git rev-parse HEAD)
Main ref: $(git rev-parse main)
Node: $(node --version)
npm: $(npm --version)
package-lock.json state: $package_lock_state

Important package-lock note:
The exact Git head did not track package-lock.json. It was generated by the CI npm version with scripts disabled so Claude can run npm ci. It is intentionally untracked and does not alter the exact implementation commit or Git bundle.

Exact deterministic M1 build command used by CI:
NODITECH_DIST_DIR=dist-milestone1 node build/assemble-pc2-ll-release.js

Exact named Node suites used by CI:
node --test tests/validation/*.test.js tests/build/*.test.js tests/engine/*.test.js

Exact integration commands used by CI:
npm run extract
npm run compile
npm run preflight
npm run offline

Required browser commands for B2 correction:
npm run chromium
npm run chromium:ll-cutover

Double-build requirement:
Run the deterministic command twice with separate NODITECH_DIST_DIR values, then compare both generated HTML files byte-for-byte and compare SHA-256 values.
EOF

cat > package-out/REQUIRED_FILES_CHECK.txt <<'EOF'
Required file checks: PASS
package.json
package-lock.json
build/assemble-pc2-ll-release.js
docs/MILESTONE1_FREEZE_TRANSITION.md
docs/MILESTONE1_IMPLEMENTATION_STATUS.md
.github/workflows/
chromium/
tests/
EOF

{
  echo "package-lock.json provenance: $package_lock_state"
  echo "Generator: npm $(npm --version) under Node $(node --version)"
  echo "Command: npm install --package-lock-only --ignore-scripts --no-audit --no-fund"
  sha256sum package-lock.json
} > package-out/PACKAGE_LOCK_PROVENANCE.txt
cp package-lock.json package-out/package-lock.json

grep -RIn --exclude-dir=.git --exclude-dir=node_modules --exclude-dir='dist*' -F 'Build 9.6-rc8' . > package-out/IDENTITY_SOURCE_LOCATIONS.txt || true
grep -RIn --exclude-dir=.git --exclude-dir=node_modules --exclude-dir='dist*' -E 'EXPECTED_PC2_SHA256|b7a1f4b597383fb877c1aa762f8103041411bd8c6ad2b78f33845a746cd63abe|27bac419f7f92d47070239520b360dbce9d20a5e2619ae02df749aaea8980cd7|ac589bca41ae0260e97779e73e727e2ab999d7a962447a5ddc3c59cdc8d1085a' . > package-out/HASH_PIN_LOCATIONS.txt || true

git ls-tree -r --name-only HEAD > package-out/HEAD_FILE_INVENTORY.txt
git status --short --branch > package-out/GIT_STATUS.txt
sha256sum package-out/noditech_m1.bundle package-out/noditech_m1_worktree.zip package-out/Noditech_repo_with_git.zip package-out/package-lock.json > package-out/PACKAGE_INPUT_SHA256SUMS.txt
